### ISSUE TITLE
SB8200 is the same as SB6183

### ISSUE THREAD

**Issue by robbiet480** [wathiede/surfer#4]
Just "added" support for my SB8200 by copying the SB6183 directory and changing references as necessary. The HTML is slightly different, but nothing that throws off the parsing code for the SB6183. Should I submit a PR with a new package for SB8200 or modify SB6183 to be called like `modern` (the SB8200 is the latest and greatest modem out of the horror show that is Motorola/Arris which is why I think `modern` might be appropriate).

Just let me know how to proceed!

**Comment by wathiede** [comment]
I think a pull request that clones and search & replaces as appropriate (with an example page under testdata/) would be ideal.

That way if they push out firmware updates that changes one but not the other, then its easier to apply a model specific fix.
